openapi: 3.0.0
info:
  title: Osmosis - gRPC Gateway docs
  description: A REST interface for state queries, legacy transactions
  version: 1.0.0
paths:
  "/osmosis/gamm/v1beta1/{poolId}":
    get:
      operationId: Pool
      responses:
        "200":
          description: A successful response.
          content:
            "*/*":
              schema:
                type: object
                properties:
                  pool:
                    type: object
                    properties:
                      id:
                        type: string
                        format: uint64
                      swapFee:
                        type: string
                      totalWeight:
                        type: string
                      token:
                        type: object
                        properties:
                          denom:
                            type: string
                          description:
                            type: string
                          totalSupply:
                            type: string
                      records:
                        type: object
                        additionalProperties:
                          type: object
                          properties:
                            denormalizedWeight:
                              type: string
                            balance:
                              type: string
        default:
          description: An unexpected error response.
          content:
            "*/*":
              schema:
                type: object
                properties:
                  error:
                    type: string
                  code:
                    type: integer
                    format: int32
                  message:
                    type: string
                  details:
                    type: array
                    items:
                      type: object
                      properties:
                        type_url:
                          type: string
                        value:
                          type: string
                          format: byte
      parameters:
        - name: poolId
          in: path
          required: true
          schema:
            type: string
            format: uint64
      tags:
        - Query
  "/osmosis/gamm/v1beta1/{poolId}/prices":
    get:
      operationId: SpotPrice
      responses:
        "200":
          description: A successful response.
          content:
            "*/*":
              schema:
                type: object
                properties:
                  spotPrice:
                    type: string
        default:
          description: An unexpected error response.
          content:
            "*/*":
              schema:
                type: object
                properties:
                  error:
                    type: string
                  code:
                    type: integer
                    format: int32
                  message:
                    type: string
                  details:
                    type: array
                    items:
                      type: object
                      properties:
                        type_url:
                          type: string
                        value:
                          type: string
                          format: byte
      parameters:
        - name: poolId
          in: path
          required: true
          schema:
            type: string
            format: uint64
        - name: tokenIn
          in: query
          required: false
          schema:
            type: string
        - name: tokenOut
          in: query
          required: false
          schema:
            type: string
      tags:
        - Query
  "/osmosis/gamm/v1beta1/{poolId}/share":
    get:
      operationId: ShareInfo
      responses:
        "200":
          description: A successful response.
          content:
            "*/*":
              schema:
                type: object
                properties:
                  shareInfo:
                    type: object
                    properties:
                      denom:
                        type: string
                      description:
                        type: string
                      totalSupply:
                        type: string
        default:
          description: An unexpected error response.
          content:
            "*/*":
              schema:
                type: object
                properties:
                  error:
                    type: string
                  code:
                    type: integer
                    format: int32
                  message:
                    type: string
                  details:
                    type: array
                    items:
                      type: object
                      properties:
                        type_url:
                          type: string
                        value:
                          type: string
                          format: byte
      parameters:
        - name: poolId
          in: path
          required: true
          schema:
            type: string
            format: uint64
      tags:
        - Query
  "/osmosis/gamm/v1beta1/{poolId}/swap_fee":
    get:
      operationId: SwapFee
      responses:
        "200":
          description: A successful response.
          content:
            "*/*":
              schema:
                type: object
                properties:
                  swapFee:
                    type: string
        default:
          description: An unexpected error response.
          content:
            "*/*":
              schema:
                type: object
                properties:
                  error:
                    type: string
                  code:
                    type: integer
                    format: int32
                  message:
                    type: string
                  details:
                    type: array
                    items:
                      type: object
                      properties:
                        type_url:
                          type: string
                        value:
                          type: string
                          format: byte
      parameters:
        - name: poolId
          in: path
          required: true
          schema:
            type: string
            format: uint64
      tags:
        - Query
  "/osmosis/gamm/v1beta1/{poolId}/tokens":
    get:
      operationId: TokenBalance
      responses:
        "200":
          description: A successful response.
          content:
            "*/*":
              schema:
                type: object
                properties:
                  tokens:
                    type: array
                    items:
                      type: object
                      properties:
                        denom:
                          type: string
                        amount:
                          type: string
                      description: >-
                        Coin defines a token with a denomination and an amount.


                        NOTE: The amount field is an Int which implements the custom method

                        signatures required by gogoproto.
        default:
          description: An unexpected error response.
          content:
            "*/*":
              schema:
                type: object
                properties:
                  error:
                    type: string
                  code:
                    type: integer
                    format: int32
                  message:
                    type: string
                  details:
                    type: array
                    items:
                      type: object
                      properties:
                        type_url:
                          type: string
                        value:
                          type: string
                          format: byte
      parameters:
        - name: poolId
          in: path
          required: true
          schema:
            type: string
            format: uint64
      tags:
        - Query
components:
  schemas:
    cosmos.base.v1beta1.Coin:
      type: object
      properties:
        denom:
          type: string
        amount:
          type: string
      description: |-
        Coin defines a token with a denomination and an amount.

        NOTE: The amount field is an Int which implements the custom method
        signatures required by gogoproto.
    google.protobuf.Any:
      type: object
      properties:
        type_url:
          type: string
        value:
          type: string
          format: byte
    grpc.gateway.runtime.Error:
      type: object
      properties:
        error:
          type: string
        code:
          type: integer
          format: int32
        message:
          type: string
        details:
          type: array
          items:
            type: object
            properties:
              type_url:
                type: string
              value:
                type: string
                format: byte
    osmosis.gamm.v1beta1.LP:
      type: object
      properties:
        denom:
          type: string
        description:
          type: string
        totalSupply:
          type: string
    osmosis.gamm.v1beta1.Pool:
      type: object
      properties:
        id:
          type: string
          format: uint64
        swapFee:
          type: string
        totalWeight:
          type: string
        token:
          type: object
          properties:
            denom:
              type: string
            description:
              type: string
            totalSupply:
              type: string
        records:
          type: object
          additionalProperties:
            type: object
            properties:
              denormalizedWeight:
                type: string
              balance:
                type: string
    osmosis.gamm.v1beta1.QueryPoolResponse:
      type: object
      properties:
        pool:
          type: object
          properties:
            id:
              type: string
              format: uint64
            swapFee:
              type: string
            totalWeight:
              type: string
            token:
              type: object
              properties:
                denom:
                  type: string
                description:
                  type: string
                totalSupply:
                  type: string
            records:
              type: object
              additionalProperties:
                type: object
                properties:
                  denormalizedWeight:
                    type: string
                  balance:
                    type: string
    osmosis.gamm.v1beta1.QueryShareInfoResponse:
      type: object
      properties:
        shareInfo:
          type: object
          properties:
            denom:
              type: string
            description:
              type: string
            totalSupply:
              type: string
    osmosis.gamm.v1beta1.QuerySpotPriceResponse:
      type: object
      properties:
        spotPrice:
          type: string
    osmosis.gamm.v1beta1.QuerySwapFeeResponse:
      type: object
      properties:
        swapFee:
          type: string
    osmosis.gamm.v1beta1.QueryTokenBalanceResponse:
      type: object
      properties:
        tokens:
          type: array
          items:
            type: object
            properties:
              denom:
                type: string
              amount:
                type: string
            description: >-
              Coin defines a token with a denomination and an amount.


              NOTE: The amount field is an Int which implements the custom method

              signatures required by gogoproto.
    osmosis.gamm.v1beta1.Record:
      type: object
      properties:
        denormalizedWeight:
          type: string
        balance:
          type: string
